# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12781eb08a0c58187c3f3315d8bae6ee47728f24602ce7eac7cdfccb54af2565a33e569542904a6d5e7d7e6954ffcba7a03ede2c5ebe3dd1fc7d4ced2364a749

test:
  secret_key_base: 000593825b9935759b9207a463fedd327fd0f7857745f0f159c410411861fce954a99454fa1c5e9e20908cd3ac15b0cd6fd929fef76bc7e7b156af064a3f1bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
